/contacts:
    
    displayName: Collection of contacts
    get:
        description: Get all contacts
    post:
        description: Insert a contacts
        body:
            application/json:
                schema: !include schemas/contacts.json

    /{id}:
        displayName: A particular contact
        get:
            description: Get a particular contact
        delete:
            description: Delete a particular contact
        patch:
            description: Update a particular contact

        /phones:
            
            displayName: Collection of phones
            get:
                description: Get all phones
            post:
                description: Insert a phones
                body:
                    application/json:
                        schema: !include schemas/phones.json
        
            /{id}:
                displayName: A particular phone
                get:
                    description: Get a particular phone
                delete:
                    description: Delete a particular phone
                patch:
                    description: Update a particular phone
                   
        /emails:
            
            displayName: Collection of emails
            get:
                description: Get all emails
            post:
                description: Insert a emails
                body:
                    application/json:
                        schema: !include schemas/emails.json

        /places:
            
            displayName: Collection of places
            get:
                description: Get all places
            post:
                description: Insert a places
                body:
                    application/json:
                        schema: !include schemas/places.json
        
            /{id}:
                displayName: A particular place
                get:
                    description: Get a particular place
                delete:
                    description: Delete a particular place
                patch:
                    description: Update a particular place
                    
/destinations:
    
    displayName: Collection of destinations
    get:
        description: Get all destinations
    post:
        description: Insert a destinations
        body:
            application/json:
                schema: !include schemas/destinations.json

    /{id}:
        displayName: A particular destination
        get:
            description: Get a particular destination
        delete:
            description: Delete a particular destination
        patch:
            description: Update a particular destination
